[package]
name = "solana-move-around"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.7.4"

[features]
test-bpf = []

[dev-dependencies]
solana-sdk = "1.7.4"

[lib]
crate-type = ["cdylib", "lib"]
